name: Programador Iniciante
description: Registrando Aprendizado
meta_description: "Programador iniciante, registrando aprendizado"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://iraecio.github.io/"
google_analytics: "UA-39355324-5"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Iraecio Carvalho"

# Disqus config
disqus-shortname: ""
